repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    args: [--config-file=pyproject.toml]
    additional_dependencies: [types-requests, types-PyYAML]
    exclude: ^tests/skills/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
    # Run the linter
    - id: ruff
      args: [ --fix ]
      exclude: ^tests/skills/
    # Run the formatter
    - id: ruff-format
      exclude: ^tests/skills/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: debug-statements
  - id: check-added-large-files
